# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpotEventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpotEventApp.Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpotEventApp.Address'),
        ),
    ]
