# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotEventApp', '0002_auto_20171102_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.CharField(default='NO_ARTISTS', max_length=100),
        ),
    ]
